# -*- coding: utf-8 -*-
"""Project 106

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k4SNL0FBmCh6JfHX8eMvjCyxwI5VlXqF
"""

import ploty.express as px
import csv
import numpy as np

def getDataSource(data_path):
  marks_in_percentage=[]
  days_present=[]
  with open(data_path) as csv_file:
    csv_reader=csv.DictReader(csv_file)
    for row in csv_reader:
      marks_in_percentage.append(float(row["Marks in Percentage"]))
      days_present.append(float(row["Days Present"]))

  return {"x":marks_in_percentage, "y":days_present}

def findCorrelation(datasource):
  correlation=np.corrcoef(datasource["x"], datasource["y"])
  print("Correlation between Marks in percentage and Days present :- \n--->", correlation[0,1])

def plotFigure(data_path):
  with open(data_path) as csv_file:
    df=csv.DictReader(csv_file)
    fig=px.scatter(df, x="Days Present", y="Marks In Percentage")
    fig.show()

from google.colab import files
def setup():
  data_path=files.upload()
  getDataSource()
  findCorrelation()
  plotFigure()

setup()